remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Análises de Séries Temporais com dados do IPEA"
description: "Trabalho realizado na Disciplina SME0808 - Séries Temporais - Segundo Semestre de 2023"
