remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Análises de Séries Temporais com dados do IPEA"
description: "Trabalho realizado na Disciplina SME0808 - Séries Temporais - Segundo Semestre de 2023"
collections:
  analises:
    output: true
    permalink: /analises/:path/ # ou qualquer estrutura de URL que você preferir
# Default values
defaults:
  - scope:
      path: "analises/html" # caminho relativo para os seus arquivos HTML de análise
    values:
      layout: default # ou qualquer outro layout que você queira usar para esses arquivos
