name: deploy-shiny

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'  # Executa todos os dias à meia-noite UTC

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{secrets.DEPLOY_SECRET}}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependency
        run: |
          install.packages(c("shiny", "rsconnect", "devtools", "rvest", "dplyr", "xml2", "XML", "httr", "faq", "slickR", "urca, fable", "ipeadatar", "tidyverse", "plotly", "shinybusy", "fpp3", "DT", "shinyWidgets", "slider", "fabletools"), type = "binary")
        shell: Rscript {0}
      - name: shinyapps deploy
        run: |
             readr::write_csv(ipeadatar::available_series("br"), "datasets.csv")
             rsconnect::setAccountInfo(name='chicodias', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')
             rsconnect::deployApp(appName = 'seriesTemporais',account = 'chicodias', server = 'shinyapps.io', forceUpdate = TRUE)
        shell: Rscript {0}
