on: [push]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{secrets.DEPLOY_SECRET}}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependency
        run: |
          install.packages(c("shiny", "rsconnect", "devtools", "rvest", "dplyr", "xml2", "XML", "httr", "faq", "slickR", "shinydashboard", "dashboardthemes", "shinycssloaders"), type = "binary")
          devtools::install_github("dgrtwo/stackr")
        shell: Rscript {0}
      - name: shinyapps deploy
        run: |
             rsconnect::setAccountInfo(name='chicodias', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')
             rsconnect::deployApp(appName = 'seriesTemporais',account = 'chicodias', server = 'shinyapps.io', forceUpdate = TRUE)
        shell: Rscript {0}
